### PR TITLE
Improvements to `brace`

### PR DESCRIPTION
**Pull request by RubixDev**
This PR adds a new style key called `outer-pointiness` for the braces from the `decorations` library. It effectively controls the same thing as the existing `pointiness` but for the outer points instead. This adds the two new debug points `i` and `j` (what was `i` before is now `k`). Setting this to `0` (as is the default) provides the same behaviour as before.

I also moved documentation of the style keys from the function's doc-comment to the `manual.typ` file just like the other elements do it.

Screenshot of the updated example:
image

I am also second guessing my choice from yesterday in #227 that a pointiness of 0 is the maximum. Intuitively I would expect 1 to be the max, but then again with the angles it makes sense to have `0deg` as the max :shrug:. If you think we should change this I could quickly edit this PR or create another one, but that would of course immediately break backwards compatibility with v0.1.2.

---

Also unrelated to the PR: I noticed the example code in the manual is justified which I think doesn't look good in code snippets. And the default font inside the example canvases is also monospace.

### CODE REVIEW

**Comment by RubixDev** [comment]
I also just noticed an issue with the flip toggle: because internally it just swaps the start and end positions the final `move-to(end)` call then actually moves to the start position, which is not what users expect. I pushed a quick fix that the move-to checks for the `flip` value.

**Comment by RubixDev** [comment]
> I pushed a quick fix that the move-to checks for the flip value.

Actually that's still not perfect when used as part of a `merge-path`. I'll work on a better fix in a bit.

**Comment by RubixDev** [comment]
> Actually that's still not perfect when used as part of a merge-path.

Ok that's resolved. Flipping now works by negating the amplitude and pointiness values, which doesn't have these issues.

Additionally I improved the assertion messages and added a `debug-text-size` style option, so this PR is now just general polishing of yesterdays work in #227.

**Review by johannes-wolf — APPROVED** [review]
LGTM.

**Pull request merged**
