### PR TITLE
Make rotations/angles consistent

### LINKED ISSUE #274: Rotations about the Z-axis
There is something I want to bring up about my original implementation of `arc-through` from #206. This was originally going to just be a comment on #273, but after typing so much I figured it was worth posting as a full issue.

```typst
#let start = {
    let (x, y, ..) = vector.sub(a, center)
    calc.atan2(x, y) // Typst's atan2 is (x,y) order!!
}
```

This part was meant to be only temporary; it's supposed to figure out the angle between `a` and the $x$-axis when `center` is taken as the origin. What this _should_ be is just a call to `vector.angle2(center, a)`; but when I tried that, I found that my angles were always backwards. That was when I discovered that Typst's `atan2` is $(x, y)$ instead of $(y, x)$, like most other `atan2` implementations. `vector.angle2`, which uses `calc.atan2`, passes its arguments as $(y, x)$ instead of Typst's $(x, y)$, which is why I wrote that little custom block with that comment (it also subtracts `a - b` instead of `b - a`, then adds 90 degrees, which I presume was done to account for the incorrect argument order).

Had I gotten around to making a full PR, I had intended to fix this as part of it. So, when I saw #273, I figured I would go ahead and do that little change as a separate one and then request to merge into this branch. But... I've managed to confuse myself.

-----

To cut to the chase: **in which direction should rotations around the $z$-axis be done?**

Is this 60&deg;, or is this &minus;60&deg;? My intuition when working in two dimensions is that it's 60&deg;, like how [the unit circle works][unit-circle]. That is, I expected a right-hand coordinate system, where counterclockwise is positive. So, 60&deg; is what I'd expect `atan2(x: 1/2, y: sqrt(3)/2)` to spit out:

```js
>>> Math.round(Math.atan2(Math.sqrt(3)/2, 1/2) * 180/Math.PI) // JS is (y, x)
60
```

There is no clear picture, as far as I can discern, for what CetZ uses, though:

<details><summary>
(diagram generated with Typst v0.8 and CetZ 2ed733a)
</summary>
<p>

(code is kind of messy, but here it is)

```typst
#import "/src/lib.typ" as cetz

#set page(width: auto, height: auto, margin: 12pt)

#cetz.canvas(length: 2.5cm, {
  import cetz.draw: *

  let origin = (0, 0)
  let point = (1/2, calc.sqrt(3)/2)
  let label = $ (1/2, sqrt(3)/2) $
  let angle = cetz.vector.angle2(origin, point)

  // Unit circle and origin dot
  circle(origin, radius: 1, stroke: gray)
  on-layer(2, { circle(origin, radius: 2pt, fill: black) })

  // Axes
  line((-1.5, 0), (1.5, 0), mark: (end: ">", stroke: black, fill: black), name: "x-axis")
  content((), padding: 0.5em, anchor: "left", $x$)
  line((0, -1.5), (0, 1.5), mark: (end: ">", stroke: black, fill: black), name: "y-axis")
  content((), padding: 0.5em, anchor: "bottom", $y$)

  // Arrow through point, label, and intersection dot
  line(origin, ((), 1.5, point), stroke: red, mark: (end: ">", stroke: red, fill: red))
  content((), anchor: "left", padding: 8pt, $#raw("p") = (1/2, sqrt(3)/2)$)
  circle(point, radius: 2pt, fill: black)

  // Angle and theta
  cetz.angle.angle(origin, (1, 0), point, radius: 1/3, stroke: red)
  content(
    (origin, 0.5, -30deg, point), anchor: "left",
    frame: "rect", fill: white, stroke: none, padding: 3pt,
    text(fill: red, $ #raw("vector.angle2(origin, p)") = #angle $)
  )

  // 45 degree blue line
  line(origin, (origin, 1.5, 45deg, point), stroke: blue)
  circle((), radius: 1pt, fill: black)
  content((), anchor: "right", padding: 5pt, text(fill: blue, `(origin, 1.5, 45deg, p)`))

  // -85 degree blue line
  line(origin, (origin, 1.5, -85deg, point), stroke: blue)
  circle((), radius: 1pt, fill: black)
  content((), anchor: "left", padding: 5pt, text(fill: blue, `(origin, 1.5, -85deg, p)`))

  // purple line
  group(name: "rotated", {
    rotate(120deg)
    line(origin, (1.5, 0), stroke: purple)
    circle((), radius: 1pt, fill: black, name: "dot")
    copy-anchors("dot")
  })
  content(
    "rotated", anchor: "right", padding: 5pt,
    text(fill: purple)[`(1.5, 0.0)` after `rotate(120deg)`]
  )

  // Arcs
  arc((-1, 0), start: 0deg, stop: -60deg, stroke: olive, name: "arc")
  circle("arc.end", radius: 1pt, fill: black)
  content(
    (), anchor: "right", padding: 5pt,
    text(fill: olive)[`arc((-1,0), start: 0deg, stop: -60deg)`]
  )

  arc((-1, 0), start: 0deg, stop: 60deg, stroke: olive, name: "arc")
  circle("arc.end", radius: 1pt, fill: black)
  content(
    (), anchor: "right", padding: 5pt,
    text(fill: olive)[`arc((-1,0), start: 0deg, stop: 60deg)`]
  )

  // Dot for arcs
  circle((-1, 0), radius: 2pt, fill: black)
})
```

</p>
</details> 

- For the current implementation of `vector.angle2`, counterclockwise is negative (left-handed; red).
- For the _Interpolation_ coordinate mode's `angle` parameter, counterclockwise is positive (right-handed; blue).
- For the `rotate` transformation function, clockwise is positive (left-handed; purple).
- For `arc`s `start`, `stop`, and `delta` parameters, counterclockwise is positive (right-handed; olive).

The `arc` one being different from `vector.angle2` is the problem I initially ran into, and what prompted that custom `start` block in my original `arc-through` function from #206. The `rotate` one could make sense either way: technically, the _coordinate space_ was rotated by 120&deg;, my line was drawn, and then it was rotated back. But that means that a call to `rotate(120deg)` rotated my _shapes_ by -120&deg;, which feels counterintuitive.

Like I alluded to, I started working on a PR to fix this: https://github.com/johannes-wolf/cetz/compare/johannes-wolf:2ed733a...matthew-e-brown:feb07cc. I "fixed" `vector.angle2` to work in-line with the trigonometric functions, and subsequently "fixed" the few spots that used `vector.angle2`. But then when making my MWE and writing my PR, I noticed that `rotate`&mdash;which didn't depend on `angle2`&mdash;also happened to be left-handed. I could "fix" the `rotate` function to also be right-handed, but because the transformation matrices feel like the "standard" way to do rotations, that felt a little drastic. I suddenly became unsure: what _is_ the intended direction of rotation for CetZ?

-----

I have been staring at matrices and curves and arcs, twisting my left and right hands around in the air for so long now that I could very well just be getting my angles in a knot. I wouldn't be too surprised if it turns out this is all completely intended behaviour and I've missed something silly. I hope not! 😆 I'll open a draft PR with my (potential) fixes for now. Once I know which way things are supposed to spin, I can correct the last few discrepancies and mark it as ready. Or, I can close it if I got things the wrong way.

One last thing I want to note is that Typst's native `rotate` function is left-handed; so clockwise is positive. Not that CetZ has to use the same system, but it certainly didn't help me come to any conclusions.

Sorry 🍁 this issue's so long. 😅

[unit-circle]: https://math.stackexchange.com/a/1749298/607863

### PR DESCRIPTION
**Pull request by matthew-e-brown**
~~See #274 for details&mdash;I'm only a _little bit_ sure this is actually a fix.~~
Closes #274.

Here's the MWE I mentioned, demonstrating that angles are still working as intended. The label on the blue line is spun around to demonstrate that its anchors and rotation follow along as they should.

<details><summary> (generated with Typst v0.8 and CetZ at feb07cc) </summary>
<p>

```typst
#import "/src/lib.typ" as cetz

#set page(width: auto, height: auto, margin: 0.5in)

#let angle2-new(a, b) = cetz.vector.angle2(a, b)
#let angle2-old(a, b) = calc.atan2(a.at(1) - b.at(1), a.at(0) - b.at(0)) + 90deg

#let test(a, a-label: $$, line-label-side: "bottom") = cetz.canvas(length: 1.75cm, {
  import cetz.draw: *
  import cetz.vector

  let o = (0, 0)

  // Grid and unit circle
  grid((-2, -2), (2, 2), step: 0.5, stroke: 0.5pt + silver)
  line((-2, 0), (2, 0), stroke: 0.25pt + black)
  line((0, -2), (0, 2), stroke: 0.25pt + black)
  circle((0, 0), radius: 1, stroke: 0.75pt + black)
  line((0, 0), (1, 0), stroke: 1pt + black) // slightly thicker

  // Vector and the two methods of drawing the lines between them
  line(o, a, stroke: (paint: blue, cap: "round"))
  arc(o, anchor: "origin", radius: 0.30, start: 0deg, stop: angle2-new(o, a), name: "arc-line")
  cetz.angle.angle(o, (1, 0), a, stroke: (dash: "dotted"), radius: 0.70, name: "angle-line")

  // Intersection dots
  set-style(circle: (radius: 0.04, fill: black, stroke: none))
  circle(o)
  circle(a)

  // Labels on point and line
  content((o, 1.20, a), angle: angle2-new(o, a), padding: 0.08, $alpha$)
  content(
    (o, 0.5, a), angle: angle2-new(o, a),
    padding: 0.11, $arrow(alpha)$, anchor: line-label-side, name: "line-label"
  )

  // Legends
  set-style(content: (frame: "rect", padding: 0.125, fill: white, stroke: 0.5pt + silver))
  content((-2, 2), padding: 0.15, anchor: "top-left", $ alpha = #a-label $)
  content((2, -2), anchor: "bottom-right", $
    #raw("angle2-new")lr(( (0,0) thin,thin alpha )) &= #angle2-new(o, a)\
    #raw("angle2-old")lr(( (0,0) thin,thin alpha )) &= #angle2-old(o, a)
  $)

  // Draw all anchors
  set-style(circle: (radius: 0.03, stroke: 0.5pt + black))

  circle("line-label.top", fill: red)
  circle("line-label.right", fill: yellow)
  circle("line-label.bottom", fill: green)
  circle("line-label.left", fill: blue)

  circle("arc-line.start", fill: purple)
  circle("arc-line.end", fill: fuchsia)

  circle("angle-line.start", fill: purple)
  circle("angle-line.end", fill: fuchsia)
})

#align(center, grid(
  columns: 2,
  gutter: 1em,
  test(( 1/2,  calc.sqrt(3)/2), a-label: $ ( 1/2 thin,thin  sqrt(3)/2) $),
  test((  -1,               0), a-label: $ (  -1 thin,thin          0) $),
  test((-1/2, -calc.sqrt(3)/2), a-label: $ (-1/2 thin,thin -sqrt(3)/2) $,  line-label-side: "top"),
  test(( 1/2, -calc.sqrt(3)/2), a-label: $ ( 1/2 thin,thin -sqrt(3)/2) $,  line-label-side: "top"),
))

#let dot(color) = box(circle(radius: 0.25em, fill: color, stroke: 0.5pt + black))
#let my-line(dash) = box(baseline: -0.25em, line(length: 1.25em, stroke: (dash: dash)))
#set terms(separator: [~=~])

#stack(dir: ltr, spacing: 2em, [
  / #dot(red): Content's `top`
  / #dot(yellow): Content's `right`
  / #dot(green): Content's `bottom`
  / #dot(blue): Content's `left`
  / #dot(purple): Line's `start`
  / #dot(fuchsia): Line's `end`
  / #my-line("solid"): Drawn using `draw.arc`
  / #my-line("dotted"): Drawn using `angle.angle`
], [
  #show par: set block(spacing: 2em)

  Content inside of Typst's `rotate` function at $20 degree$\
  (and therefore also CetZ's `content`'s previous behaviour):
  #align(center, rotate(20deg, [Hello!]))

  CetZ's updated `content` function with an angle of $20 degree$:
  #align(center, cetz.canvas({ cetz.draw.content((), angle: 20deg, [Hello!]) }))
])
```

</p>
</details>

### CODE REVIEW

**Comment by fenjalien** [comment]
Thanks for the fixes! @johannes-wolf can this be merged into `redesign-internals` before the arc-through PR?

@matthew-e-brown Do you mind adding fixes to make sure all the rotation stuff goes in the same direction? like `rotate` and angle coordinates :)

**Comment by johannes-wolf** [comment]
Yes, this can go into `redesign-internals`.

**Comment by matthew-e-brown** [comment]
> Do you mind adding fixes to make sure all the rotation stuff goes in the same direction? like rotate and angle coordinates :)

Sure 🙂 I will take a look at the other styles of rotation as soon as I finish up the homework that this distracted me from 😆 Hopefully later tonight or tomorrow morning.

**Comment by matthew-e-brown** [comment]
@johannes-wolf Since my branch is based off of your `cetz-206-arc-through` already, it's already got 2ed733a in it. Merging this into `redesign-internals` would just supercede #273, wouldn't it? Is that alright?

**Comment by fenjalien** [comment]
> Sure 🙂 I will take a look at the other styles of rotation as soon as I finish up the homework that this distracted me from 😆 Hopefully later tonight or tomorrow morning.

Thanks and good luck!

>Since my branch is based off of your cetz-206-arc-through already, it's already got https://github.com/johannes-wolf/cetz/commit/2ed733a33cf087e38b1a5b04e4e09b642960fdfc in it. Merging this into redesign-internals would just supercede https://github.com/johannes-wolf/cetz/pull/273, wouldn't it? Is that alright?

No as we'll squash commit so the arc-through commit would get lost. Either #273 gets merged first or this pr rebases onto the current head of redesign-internals.

**Comment by johannes-wolf** [comment]
Your example picture look very nice btw. :+1:

**Review by johannes-wolf — APPROVED** [review]

**Comment by johannes-wolf** [comment]
Can this get merged @matthew-e-brown?

**Comment by matthew-e-brown** [comment]
Hi @johannes-wolf sorry for disappearing. I said I'd finish up my schoolwork and then get to this PR, but my university had other plans. I've been **beyond** busy for the last few weeks. 🫠🪦

If I recall correctly I still had yet to look into the rotation matrices before un-drafting it. I believe it was finding a problem with the matrices, even after making my other tweaks, that made me decide to open that big issue—so I think they were definitely on my checklist. Of course I also wanted to do a full scan through and look at all the other places where rotations were used, and make sure nothing was broken and that all their angles were correct. Finally I was hoping to add a test or two if needed. 

That said, I believe the commits that are already here are totally fine. So this _could_ be merged if you wanted to get it in for the next version, but I'm pretty sure (again, it's been a while) there are a few more tweaks to make. At the very least, there's a few _double checks_ to do.

I would love to be the one to finish up this PR because I'd be proud to contribute, but I'd hate for it to hold things up. So if someone else wants to take over this fix to get it across the finish line, I'd be cool with that. If not, I promise I haven't forgotten about it! 😅 I'd love to get back to it eventually. I'll be back into using Typst for another assignment soon, so I may be able to find an hour or two to poke around in CetZ sometime this weekend... but that is still a ways away.

Let me know what you'd like to do. Sorry again!! 🍁

**Comment by johannes-wolf** [comment]
I'll wait, take your time. :)

**Comment by johannes-wolf** [comment]
I discovered that the rotation matrix for xyz euler angles was wrong, so I fixed it and also changed the `rotate(..)` function to use CCW angles. See #324.

**Comment by matthew-e-brown** [comment]
Hi @johannes-wolf, I see there's been quite a lot of work done since I last looked into this. Notably, the `redesign-internals` PR is gone (did that become the `0.2.0` branch?), and #324 seems to add a general transformation function.

I feel like it would make sense to rebase this to a more up-to-date starting point, to avoid double-checking and fixing things that have already been reworked (e.g. all the matrices you guys've been working on). Or do you think it still makes sense to merge it into `206-arc-through`? Let me know how you think I should proceed. I wouldn't be surprised if the interals-redesign process has already covered all the things in this PR! 😄

**Comment by johannes-wolf** [comment]
Hi @matthew-e-brown, yes, the `redesign-internals` branch got renamed to `0.2.0`. I think you should rebase on that branch and we merge `arc-through` after merging this PR.

**Comment by matthew-e-brown** [comment]
Alright, rebased onto `0.2.0`.

Hopefully removing the `*-1`'s in fb54cf28bbfde2a14ad0716731f8866b87654da9 doesn't break anything from `v0.2.0`... it didn't break anything back in October, but there was a 73-commit difference between the branches! 😄

**Comment by johannes-wolf** [comment]
> Alright, rebased onto `0.2.0`.
> 
> Hopefully removing the `*-1`'s in [fb54cf2](https://github.com/johannes-wolf/cetz/commit/fb54cf28bbfde2a14ad0716731f8866b87654da9) doesn't break anything from `v0.2.0`... it didn't break anything back in October, but there was a 73-commit difference between the branches! 😄

Can you drop the `arc-through` commit from this PR please? The CI tests should fail. Are you able to commit new test images or should I do that?

**Comment by matthew-e-brown** [comment]
Oh, right... Not gonna lie, it totally slipped my mind that I could do that with a rebase 🤣

**Comment by matthew-e-brown** [comment]
@johannes-wolf I can commit new test images if you'd like, but there's a small problem... The rotations being "correct" now (i.e., reversed; always CCW), means that tests that had manually-rotated things have flipped labels now. Mostly, that's the charts:




Other things are also flipped, but those're mostly inconsequential:



Should I go in an flip these labels' angles before committing?

**Comment by johannes-wolf** [comment]
That would be nice, yes :)

**Comment by matthew-e-brown** [comment]
Alright, ran the script. I checked the images that differed, and they all seem to be free of major visual changes.

Only thing is that running it on Typst v0.9.0 means that some of the `U+002D HYPHEN -` in axis labels became `U+2122 MINUS −`, which makes a few tick markers a tiny bit wider. Hopefully that's okay. I'd have to roll-back my Typst install to undo that; but, the reference images are bound to update to v0.9.0 eventually anyways... 😁

**Comment by matthew-e-brown** [comment]
Ah, whoops... I updated Typst to 0.9.0 on my laptop and re-generated the images there—but then this morning I fixed the labls on my desktop and re-ran it... which I have not yet updated to 0.9.0.

One sec!!

**Comment by matthew-e-brown** [comment]
Much better. Now the only tests with changes are the `content` and `content/rotate`. That makes more sense. 🙂

**Review by johannes-wolf — APPROVED** [review]

**Comment by johannes-wolf** [comment]
Merged :) Thank you!

**Pull request merged**
