### PR TITLE
feat(decorations): add flat-brace

### PR DESCRIPTION
**Pull request by RubixDev**
This PR adds a second kind of brace which isn't just composed of two bezier curves, but four small curves plus two straight lines. This is the same approach as used by TikZ: https://github.com/pgf-tikz/pgf/blob/6e5fd71581ab04351a89553a259b57988bc28140/tex/generic/pgf/libraries/decorations/pgflibrarydecorations.pathreplacing.code.tex#L136-L185. It has the advantage that the spike's position doesn't have to be in the center of the brace and it generally looks better for small amplitudes.

Screenshot of the example in the manual:
image

### CODE REVIEW

**Comment by johannes-wolf** [comment]
Can you add a test for flat-brace, please? Looks pretty good!

**Comment by RubixDev** [comment]
Sure

**Review by johannes-wolf — APPROVED** [review]
:)

**Comment by ParaN3xus** [comment]
There might be a bug while using `flat-brace` with `anchor`.

For example, I expected to get a `flat-brace` pointing to point O and B (whose anchor is defined in the plot), but the direction seems to be wrong.
PixPin_2024-03-02_10-15-22

Same code with `brace` won't produce this issue.
PixPin_2024-03-02_10-15-43

Code in pictures:
```
#let c=3
#cetz.canvas(length: 2.5cm, 
{
  import cetz.draw: *
  import cetz.plot

  plot.plot(
    size: (2.6, 2.6),
    axis-style: "school-book",

    x-max: 8.5,
    x-min: -1.5,
    y-max: 8.5,
    y-min: -1.5,

    x-tick-step: 5,
    x-minor-tick-step: 1,
    y-tick-step: 5,
    y-minor-tick-step: 1,

    x-grid: "both",
    y-grid: "both",

    name: "p",
    {
      plot.add(
        axes: ("x", "y"),
        
        domain: (-2, 11), x => (x * x - c * c)/(2 * c)
      )
      plot.add(
        axes: ("x", "y"),
        domain: (-2, 11), x => -1 / 2 *  (x - 6) + 4.5
      )
      plot.add(
        axes: ("x", "y"),
        domain: (0, 6), x => 4.5 / 6 * x
      )

      plot.add-anchor("O", (0, 0))
      plot.add-anchor("A", (6, 4.5))
      plot.add-anchor("B", (0, 7.5))
    }
  )
  
  circle("p.O", radius: 0.03, name: "pointO")
  content((rel: (-0.1, 0.1)), $O$)

  circle("p.A", radius: 0.03)
  content((rel: (0.1, 0.1)), $A$)

  circle("p.B", radius: 0.03)
  content((rel: (0.1, 0.1)), $B$)

  cetz.decorations.brace("p.B", "p.O")

})
```

**Pull request merged**
