### PR TITLE
Path Decorations

### PR DESCRIPTION
**Pull request by johannes-wolf**
Adds some path replacing decorations:
- Zig-zag (sawtooth and triangle waves)
- Wave (wave drawn using a catmull curve)
- Coil/Loops

**TODOs**
- [x] Add documentation
- [x] Fix 3D paths (add an up-vector)

### CODE REVIEW

**Comment by Leedehai** [comment]
Ooh I so want this feature.. idea: beside the zig-zag and sine springs, could the "spring" also have loops? Like the upper diagram below. Also, can the spring's lines (zig-zag, sine, loops) be curved, too? Like the second example in the diagram above. These two will make drawing for engineering much easier.

**Comment by Leedehai** [comment]
Hi, I'd like to suggest adding looping springs. Here's my _draft_ code:
```typ
/// Draw a stretched loop spring
#let loop(start, end, name: none, ..style) = draw.group(name: name, ctx => {
  let style = (width: 1, stroke: auto)
  let STEP = style.width / 5

  let start = coordinate.resolve(ctx, start)
  let end = coordinate.resolve(ctx, end)
  let dir = vector.sub(end, start)
  let dist = calc.sqrt(calc.pow(dir.at(0),2) + calc.pow(dir.at(1),2))
  let N = calc.ceil(dist / STEP) // Not calc.floor, to ensure >= 1
  let degree = if dir.at(0) != 0 {
    let quo = calc.abs(dir.at(1)/dir.at(0))
    if dir.at(0) > 0 and dir.at(1) >= 0 {
      calc.atan(quo)
    } else if dir.at(0) > 0 and dir.at(1) <= 0 {
      360deg - calc.atan(quo)
    } else if dir.at(0) < 0 and dir.at(1) >= 0 {
      180deg - calc.atan(quo)
    } else {
      180deg + calc.atan(quo)
    }
  } else if dir.at(1) > 0 { 90deg } else { 270deg }

  draw.translate(start)
  draw.rotate((z: -degree))
  draw.group({
    let overshot = 1.5 // Larger value => larger loop
    let dir2 = vector.add((0,0,0), (dist,0,0))
    for i in range(0, N, step: 1) {
      let a = vector.add((0,0,0), vector.scale(dir2, (i+0) / N))
      let b = vector.add((0,0,0), vector.scale(dir2, (i+1) / N))
      if i == N - 1 {
        draw.line(a, b)
        continue
      }
      let e = vector.add((0,0,0), vector.scale(dir2, (i+overshot) / N))
      let ab = vector.sub(b, a)
      let ab-dist = calc.sqrt(calc.pow(ab.at(0), 2) + calc.pow(ab.at(1), 2))
      draw.arc(
        a, start: 135deg, stop: 45deg, radius: ab-dist*overshot/1.414)
      draw.arc(
        b, start: 135deg, delta: 270deg, radius:ab-dist*(overshot - 1)*0.707)
    }
  })
})
```

Testing:
```typ
#cetz.canvas(length: 1cm, {
  draw.circle((0,0), radius: 0.1, fill: red)
  draw.circle((0,0), radius: 1, stroke: gray)
  loop((0,0), (1,0))
  loop((0,0), (-1,2))
  loop((0,0), (-1,-3))
  loop((0,0), (0,-1.5))

  loop((3,0), (4,0))
  loop((3,0), (2,2))
  loop((3,0), (2,-3))
  loop((3,0), (3,-1.5))
})
```



(Feel free to use my code; a credit would be nice :) )

**Comment by johannes-wolf** [comment]
Thank you, @Leedehai, I've added your Implementation:
grafik

**Comment by johannes-wolf** [comment]
@Leedehai I've changed the implementation to a simpler one I came up with, that uses only two beziers per loop and also has more consistent end segments. Please re-test if it generates the kind of coil-like lines you expect.

**Comment by Leedehai** [comment]
> I've changed the implementation to... Please re-test if it generates the kind of coil-like lines you expect.

Thanks, it looks fine! Though on commit [8cef3f6](https://github.com/johannes-wolf/cetz/pull/329/commits/8cef3f602d47b10f32c50ed97750c660bf22787e) the start and end anchors on `coil` and `wave` are wrong if the path not on the x-axis. (anchors were okay at commit [35ee6de](https://github.com/johannes-wolf/cetz/commit/35ee6deb9ee81fb394ca662ccd17ae1f780801f0) I checked out earlier)

```typ
#cetz.canvas({
  cetz.draw.line((0,0), (5,0), stroke: red)

  cetz.decorations.coil(cetz.draw.line((0,0),(2,0)), name: "l1")
  cetz.draw.circle("l1.start", radius: 0.1, fill: red)
  cetz.draw.circle("l1.mid", radius: 0.1, fill: orange)
  cetz.draw.circle("l1.end", radius: 0.1, fill: blue)

  cetz.decorations.coil(cetz.draw.line((3,1),(5,2)), name: "l2")
  cetz.draw.circle("l2.start", radius: 0.1, fill: red)
  cetz.draw.circle("l2.mid", radius: 0.1, fill: orange)
  cetz.draw.circle("l2.end", radius: 0.1, fill: blue)
})
```

 (same issue if `coil` is replaced with `wave`)

**Comment by johannes-wolf** [comment]
> > I've changed the implementation to... Please re-test if it generates the kind of coil-like lines you expect.
> 
> Thanks, it looks fine! Though on commit [8cef3f6](https://github.com/johannes-wolf/cetz/pull/329/commits/8cef3f602d47b10f32c50ed97750c660bf22787e) the start and end anchors on `coil` and `wave` are wrong if the path not on the x-axis. (anchors were okay at commit [35ee6de](https://github.com/johannes-wolf/cetz/commit/35ee6deb9ee81fb394ca662ccd17ae1f780801f0) I checked out earlier)
> 
> ```typst
> #cetz.canvas({
>   cetz.draw.line((0,0), (5,0), stroke: red)
> 
>   cetz.decorations.coil(cetz.draw.line((0,0),(2,0)), name: "l1")
>   cetz.draw.circle("l1.start", radius: 0.1, fill: red)
>   cetz.draw.circle("l1.mid", radius: 0.1, fill: orange)
>   cetz.draw.circle("l1.end", radius: 0.1, fill: blue)
> 
>   cetz.decorations.coil(cetz.draw.line((3,1),(5,2)), name: "l2")
>   cetz.draw.circle("l2.start", radius: 0.1, fill: red)
>   cetz.draw.circle("l2.mid", radius: 0.1, fill: orange)
>   cetz.draw.circle("l2.end", radius: 0.1, fill: blue)
> })
> ```
> 
>   (same issue if `coil` is replaced with `wave`)

Should be fixed now.

**Comment by johannes-wolf** [comment]
I would like to wait for a review by @fenjalien. But this should be ready to be merged :)
Adding mark-support for merge-path should be done in a follow-up PR.

**Comment by johannes-wolf** [comment]
For some reason, all the test images changed some bytes.

**Pull request merged**
