### PR TITLE
The `top` and `bottom` anchor on circle were the wrong way round

### PR DESCRIPTION
**Pull request by Jollywatt**
I’m on macOS and many of the tests fail (do people get imperceptible differences from system to system?), but I’m only updating the two tests that should be affected but this fix.

### CODE REVIEW

**Comment by johannes-wolf** [comment]
Thank you! This is a known issue that got fixed in the upcoming 0.2.0 branch called `redesign-internals`. But because of the many changes, that version has not been released yet.

I wonder if we should release a tiny 0.1.3 from master which just fixes these annoying bugs? @fenjalien

**Review by johannes-wolf — APPROVED** [review]
LGTM.

**Comment by johannes-wolf** [comment]
Which tests fail for you, @Jollywatt? Sometimes tests start failing with new Typst versions because of tiny spacing/layout changes.

**Comment by fenjalien** [comment]
> I wonder if we should release a tiny 0.1.3 from master which just fixes these annoying bugs?

Hmm theres a mix of pros and cons but for the sake of using my free time well I would like to focus on finishing 0.2...

**Comment by johannes-wolf** [comment]
> > I wonder if we should release a tiny 0.1.3 from master which just fixes these annoying bugs?
> 
> Hmm theres a mix of pros and cons but for the sake of using my free time well I would like to focus on finishing 0.2...

Then we don't.

**Pull request closed without merging**
