### PR TITLE
0.2.0

### PR DESCRIPTION
**Pull request by johannes-wolf**

### CODE REVIEW

**Comment by JuliDi** [comment]
What's the roadmap/timeline for this?
And is it worth waiting for 0.2.0 before starting any major plots with cetz, i.e., will the (breaking) changes require much rework?

If there are any blockers for the release, how could I help resolving them?

**Comment by johannes-wolf** [comment]
> What's the roadmap/timeline for this? And is it worth waiting for 0.2.0 before starting any major plots with cetz, i.e., will the (breaking) changes require much rework?

The plotting API should not change (much) between 1.2 and 2.0. But 1.2 lacks some feature and plot types such as box-plots, contour-plots and filling areas between plots. Plot filling has
also been improved a lot. If you want to do plots, you do not have to wait for 2.0 imo.

Most breaking changes will occur in usage of element anchors, as the names changed to TikZ
style compass direction names (north, south, ...), see #258. But otherwise the user API should be quite stable.

> If there are any blockers for the release, how could I help resolving them?

- The new anchor system (callback based) is not ready yet (WIP #258)
- Mark positioning has not been re-implemented (waiting for the anchors)

**Comment by JuliDi** [comment]
Thanks for the heads-up, that sounds good. I'm mainly interested in the legends PR because I feel like plotting functions works really smoothly for the most part and having an auto-generated legend would make this much more pleasant to use.
But as I understand that PR is based on the 0.2 branch and will probably not work with the 0.1.x version.

**Comment by johannes-wolf** [comment]
There is no plan for releasing before 0.2.0, so you will have to wait a bit. If you are interested, feel free to pick the PR up. I am not sure when I will have time for it.

**Pull request closed without merging**
